name: Build Quickstart PDFs
on:
  push: { tags: ['v*'] }
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Render PDFs (white background)
        run: |
          find docs -name "quickstart.md" -print0 | while IFS= read -r -d '' f; do
            out="${f%.md}.pdf"
            pandoc "$f" -o "$out" \
              --pdf-engine=xelatex \
              -V geometry:margin=1in \
              -V colorlinks=true -V urlcolor=blue
          done
      - name: Upload PDFs to release
        uses: softprops/action-gh-release@v2
        with: { files: "docs/**/quickstart.pdf" }
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
