name: Build checksums
on:
  push:
    tags:
      - "v*"

jobs:
  sha256:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Adjust the glob(s) to what you actually ship with a release.
      # Avoid huge images; keep those private or host elsewhere.
      - name: Generate SHA256SUMS.txt
        run: |
          mkdir -p releases
          # Example: include PDFs, scripts, configs
          find docs -name "quickstart.pdf" -type f -print0 | xargs -0 -I{} sha256sum "{}" >> releases/SHA256SUMS.txt || true
          find scripts -type f -name "*.sh" -print0 | xargs -0 -I{} sha256sum "{}" >> releases/SHA256SUMS.txt || true
          find config -type f -maxdepth 2 -print0 | xargs -0 -I{} sha256sum "{}" >> releases/SHA256SUMS.txt || true
          sort -o releases/SHA256SUMS.txt releases/SHA256SUMS.txt
          echo "== SHA256SUMS.txt =="
          cat releases/SHA256SUMS.txt

      - name: Upload checksum as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SHA256SUMS
          path: releases/SHA256SUMS.txt

      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: releases/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
