name: ShellCheck
on:
  push: { paths: ['scripts/**/*.sh'] }
  pull_request:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@v2
